blogs/urls.py
from django.urls import path
from django.conf.urls import url

from blogs import views

app_name = 'blogs'
urlpatterns = [
    path('', views.blog_page, name="blog_page"),
    path('<year>/<month>', views.blog_by_year_month_page, name="blog_by_year_month_page"),
    path('post-comment/', views.post_comment_view, name='post_comment'),
    path('unset/', views.unset, name="unset"),
    path('<slug:slug>/', views.blog_post, name="blog_post"),
    path('category/<int:id>/', views.blog_category, name="blog_category"),
]

faqs/urls.py
from django.urls import path

from faqs import views

app_name = 'faqs'
urlpatterns = [
    path('', views.faq, name="faq"),
    path('new/', views.faq_new, name="faq_new"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from eshop import views, urls
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_page, name="index_page"),
    path('integrations', views.integrations, name="integrations_page"),
    path('case-studies', views.case_studies, name="case_studies_page"),
    path('partners', views.partners, name="partners_page"),
    path('privacy', views.privacy, name="privacy_page"),
    path('service', views.service, name="service_page"),
    path('terms', views.terms, name="terms_page"),
    path('integrations/<accounting>', views.integrations_acounting, name="integrations_acounting_page"),
    path('apps/<app>', views.product_details, name="product_details_page"),
    path('landing', include("eshop.urls")),
    path('faq/', include('faqs.urls'), name="faq_home"),
    path('blog/', include('blogs.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from eshop.models import App, default_app


# Create your models here.


class PostCategory(models.Model):
    name = models.CharField("Enter PostCategory Name", max_length=255, null=True, blank=True)
    description = models.TextField("Enter PostCategory Description", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {}".format(self.name, self.description, self.created_at, self.updated_at)

    class Meta:
        verbose_name = "Post Category Management"
        verbose_name_plural = "Post Category Management"


class Post(models.Model):
    category = models.ForeignKey(PostCategory, on_delete=models.CASCADE, related_name="post_category_set")
    title = models.CharField("Enter Post Tittle", max_length=255, null=True, blank=True)
    slug = models.SlugField("Enter Post slug", max_length=255, null=True, blank=True)
    feature_image = models.ImageField("Select Feature Image", upload_to="blogs", null=True, blank=True)
    content = RichTextUploadingField(verbose_name="Enter Post Content", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def get_feature_image_url(self):
        if self.feature_image and hasattr(self.feature_image, 'url'):
            return self.feature_image.url
        else:
            return "#"

    def __str__(self):
        return "{} - {}".format(self.category, self.title, self.feature_image, self.slug, self.content,
                                self.created_at, self.updated_at)

    class Meta:
        verbose_name = "Post Management"
        verbose_name_plural = "Post Management"


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post_comment_post_set")
    name = models.CharField(max_length=255, null=False)
    email = models.EmailField(null=False)
    website = models.CharField(max_length=255, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    is_approved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {}".format(self.post, self.name, self.email, self.website, self.comment,
                                self.is_approved,
                                self.created_at, self.updated_at)

    class Meta:
        verbose_name = "Post Comment Management"
        verbose_name_plural = "Post Comment Management"


class RelatedPost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="related_post_post")
    related = models.ManyToManyField(Post, related_name="related_post_related")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {}".format(self.post, self.related,
                                self.created_at, self.updated_at)

    class Meta:
        verbose_name = "Related Post Management"
        verbose_name_plural = "Related Post Management"

blogs/forms.py
from django import forms

from blogs.models import PostComment


class PostCommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ['post','name','email','website','comment']

blogs/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import simplejson as json
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic import View
from django.db.models import Count, Q

# Create your views here.
from blogs.forms import PostCommentForm
from blogs.models import Post, PostCategory, RelatedPost


def blog_page(request):
    category_name = request.GET.get('category', None)
    search = request.GET.get('search', None)
    if category_name:
        post_all = Post.objects.filter(category__name=category_name)
    elif search:
        post_all = Post.objects.filter(Q(title__icontains=search) | Q(content__icontains=search))
    else:
        post_all = Post.objects.all()
    category_all = PostCategory.objects.all()
    category_post_count = [{'name': category.name, 'count': Post.objects.filter(category__id=category.id).count()} for
                           category in
                           category_all]
    paginator = Paginator(post_all, 5)
    page = request.GET.get('page')
    try:
        post_data = paginator.page(page)
    except PageNotAnInteger as ex1:
        print("PAGE NOT INTEGER: ", ex1)
        post_data = paginator.page(1)
    except EmptyPage as ex2:
        print("PAGE EMPTY: ", ex2)
        post_data = paginator.page(paginator.num_pages)
    return render(request, 'blogs/blog_page.html',
                  {'post_data': post_data, 'category_data': category_post_count, 'year_range': range(2020, 2030),
                   'month_range': get_months()})


def blog_by_year_month_page(request, year, month):
    post_all = Post.objects.filter(
        created_at__year__gte=year,
        created_at__month__gte=month,
        created_at__year__lte=year,
        created_at__month__lte=month
    )
    category_all = PostCategory.objects.all()
    category_post_count = [{'name': category.name, 'count': Post.objects.filter(category__id=category.id).count()} for
                           category in
                           category_all]

    paginator = Paginator(post_all, 5)
    page = request.GET.get('page')
    try:
        post_data = paginator.page(page)
    except PageNotAnInteger as ex1:
        print("PAGE NOT INTEGER: ", ex1)
        post_data = paginator.page(1)
    except EmptyPage as ex2:
        print("PAGE EMPTY: ", ex2)
        post_data = paginator.page(paginator.num_pages)

    return render(request, 'blogs/blog_page.html',
                  {'post_data': post_data, 'category_data': category_post_count, 'year_range': range(2020, 2030),
                   'month_range': get_months()})


def blog_post(request, slug):
    post = get_object_or_404(Post, slug=slug)

    category_all = PostCategory.objects.all()
    category_post_count = [{'name': category.name, 'count': Post.objects.filter(category__id=category.id).count()} for
                           category in
                           category_all]
    return render(request, 'blogs/blog_post.html',
                  {'post': post,
                   'category_data': category_post_count,
                   'year_range': range(2020, 2030),
                   'month_range': get_months()})


def blog_category(request, id):
    post_data = Post.objects.filter(category=id)
    return render(request, 'blogs/blog_category.html', {'post_data': post_data})


def post_comment_view(request):
    if request.method == "POST":
        form = PostCommentForm(request.POST)
        post_id = request.POST.get('post')
        post = get_object_or_404(Post, pk=post_id)
        if form.is_valid():
            instance = form.save()
            request.session['comment'] = '1'
            return redirect('blogs:blog_post', slug=post.slug)
        return redirect('blogs:blog_post', slug=post.slug)


def unset(request):
    request.session['comment'] = None
    data = {"success": True, "message": "Session Unset"}
    return HttpResponse(json.dumps(data), content_type='application/json')


def get_monthsa():
    return ['January','February','March','April','May','June','July','August','September','October','November','December']
def get_months():
    return [
        {
            'name': 'January',
            'num': 1
        },
        {
            'name': 'February',
            'num': 2
        },
        {
            'name': 'March',
            'num': 3
        },
        {
            'name': 'April',
            'num': 4
        },
        {
            'name': 'May',
            'num': 5
        },
        {
            'name': 'June',
            'num': 6
        },
        {
            'name': 'July',
            'num': 7
        },
        {
            'name': 'August',
            'num': 8
        },
        {
            'name': 'September',
            'num': 9
        },
        {
            'name': 'October',
            'num': 10
        },
        {
            'name': 'November',
            'num': 11
        },
        {
            'name': 'December',
            'num': 12
        }
    ]

blogs/templates/blogs/blog_category.html
{% extends 'base-landing.html' %}
{% load static %}
{% load humanize %}
{% block content %}
{% include 'header.html' %}


         <section class="breadcrumb_area">
            <img class="breadcrumb_shap" src="{% static 'asset/img/breadcrumb/banner_bg.png' %} " alt="">
            <div class="container">
                <div class="breadcrumb_content text-center">
                    <h1 class="f_p f_700 f_size_50 w_color l_height50 mb_20">BLOG CATEGORY</h1>
                    <p class="f_400 w_color f_size_16 l_height26">{{ post.category.name }}</p>
                </div>
            </div>
        </section>

        <section class="blog_area_two sec_pad">
            <div class="container">
                <div class="row">
                <div class="col-lg-4">
                        <div class="blog-sidebar">
                            <div class="widget sidebar_widget search_widget_two">
                                <form action="#" class="search-form input-group">
                                    <input type="search" class="form-control widget_input" placeholder="Search">
                                    <button type="submit"><i class="ti-search"></i></button>
                                </form>
                            </div>
                            
                            <div class="widget sidebar_widget categorie_widget_two mt_60">
                                <h3 class="widget_title_two text-left">Categories</h3>
                                <ul class="list-unstyled">
                               {% for category in category_data %}
                                        <li> <a href="#"><span>{{category.name}}</span><em>({{category.count}})</em></a> </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            
                            <div class="widget sidebar_widget instagram_widget mt_60">
                                <h3 class="widget_title_two text-left">Archive</h3>
                                <div class="form-group"> <!-- Date input -->
                            <!-- <input class="form-control" id="date" name="date" placeholder="Select Archive" onchange="myFunc();" type="month" min="" value=""/> -->
                            <select class="form-control" onchange="document.location.href=this.value">

                                <option selected value> Select Date </option>
                                {% for y in year_range %}
                                    {% for m in month_range %}
                                        <option value="{% url 'blogs:blog_by_year_month_page' year=y month=m.num %}"> {{m.name}} - {{y}} </option>
                                    {% endfor %}
                                {% endfor %}
                            </select>
                        
                        </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8 blog_grid_info">
                        <div class="row">

                            {% if post_data.count > 0 %}
                                {% for post in post_data %}

                            <div class="col-lg-6">
                                <div class="blog_list_item blog_list_item_two">
                                    <a href="{% url 'blogs:blog_post' post.slug %}" class="post_date">
                                        <h2>{{ post.created_at|date:"d" }} <span>{{ post.created_at|naturaltime }}</span></h2>
                                    </a>
                                    <a href="{% url 'blogs:blog_post' post.slug %}"><img class="img-fluid myimg-fluid-1" src="{{ post.get_feature_image_url }}" alt="{{post.title}}"></a>
                                    <div class="blog_content">
                                        <a href="{% url 'blogs:blog_post' post.slug %}">
                                            <h5 class="blog_title">{{ post.title }}</h5>
                                        </a>
                                        <p>{{ post.content|safe|truncatewords:50 }}</p>
                                        <div class="post-info-bottom">
                                            <a href="{% url 'blogs:blog_post' post.slug %}" class="learn_btn_two">Read More <i class="arrow_right"></i></a>
                                            <a class="post-info-comments" href="{% url 'blogs:blog_category' post.category.id %}">
                                                <i class="icon_comment_alt" aria-hidden="true"></i>
                                                <span>{{ post.title }}">{{ post.category.name }}</span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                                {% endfor %}
                            {% else %}
                                <h2>No Blog Post Yet</h2>
                            {% endif %}

                        </div>
                        <ul class="list-unstyled page-numbers shop_page_number text-left mt_30">
                        {% if post_data.has_previous %}
                         <li><a class="next page-numbers" href="?page={{post_data.previous_page_number}}"><i class="ti-arrow-left"></i></a></li>
                         {% endif %}
                            <li><span aria-current="page" class="page-numbers current">{{post_data.number}}</span></li>

                            <li><a class="page-numbers"> {{post_data.paginator.num_pages}}</a></li>

                            {% if post_data.has_next %}
                            <li><a class="next page-numbers" href="#"><i class="ti-arrow-right"></i></a></li>
                            {% endif %}
                        </ul>
                    </div>
                    
                </div>
            </div>
        </section>

{% include 'footer.html' %}
{% endblock %}

blogs/templates/blogs/blog_post.html
{% extends 'base-landing.html' %}
{% load static %}
{% block content %}
{% include 'header.html' %}


         <section class="breadcrumb_area_two">
            <ul class="list-unstyled bubble">
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
            <img class="breadcrumb_shap" src="{% static 'asset/img/breadcrumb/banner_bg.png' %}" alt="">
            <div class="container">
                <div class="breadcrumb_content text-center">
                    <h1 class="f_p f_700 f_size_50 w_color l_height50 mb_20" style="color: #fff">{{ post.title }}</h1>
                    <p class="f_400 w_color f_size_16 l_height26" style="color: #fff">Published On {{ post.created_at|date:"D d M Y" }}</p>
                </div>
            </div>
        </section>

        <section class="blog_area_two sec_pad">
            <div class="container">
                <div class="row">
                <div class="col-lg-3">
                        <div class="blog-sidebar">
                            <div class="widget sidebar_widget search_widget_two">
                                <form action="#" class="search-form input-group">
                                    <input type="search" class="form-control widget_input" placeholder="Search">
                                    <button type="submit"><i class="ti-search"></i></button>
                                </form>
                            </div>

                            <div class="widget sidebar_widget categorie_widget_two mt_60">
                                <h3 class="widget_title_two text-left">Categories</h3>
                                <ul class="list-unstyled">
                                    {% for category in category_data %}
                                        <li> <a href="{% url 'blogs:blog_page' %}?category={{category.name}}"><span>{{category.name}}</span><em>({{category.count}})</em></a> </li>
                                    {% endfor %}

                                </ul>
                            </div>

                            <div class="widget sidebar_widget instagram_widget mt_60">
                                <h3 class="widget_title_two text-left">Archive</h3>

                        <div class="form-group"> <!-- Date input -->
                            <!-- <input class="form-control" id="date" name="date" placeholder="Select Archive" onchange="myFunc();" type="month" min="" value=""/> -->
                            <select class="form-control" onchange="document.location.href=this.value">

                                <option selected value> Select Date </option>
                                {% for y in year_range %}
                                    {% for m in month_range %}
                                        <option value="{% url 'blogs:blog_by_year_month_page' year=y month=m.num %}"> {{m.name}} - {{y}} </option>
                                    {% endfor %}
                                {% endfor %}
                            </select>

                        </div>

                                </ul>
                            </div>
                        </div>
                    </div>


                     <div class="col-lg-9 blog_sidebar_left">
                        <div class="blog_single mb_50" id="{{post.id}}">
                            <img class="img-fluid myimg-fluid-2" src="{{ post.get_feature_image_url }}" alt="">
                            <div class="blog_content">
                                <div class="post_date">
                                    <h2>{{ post.created_at|date:"d" }}<span>{{ post.created_at|date:"M" }}</span></h2>
                                </div>
                                <div class="entry_post_info">

                                    <a href="{% url 'blogs:blog_category' post.category.id %}">{{ post.category.name }}</a>
                                </div>
                                <a>
                                    <h5 class="f_p f_size_20 f_500 t_color mb-30">{{ post.title }}</h5>
                                </a>

                                <p class="f_400 mb_40">{{ post.content|safe }}</p>
                                <!-- <blockquote class="blockquote mb_40">
                                    <h6 class="mb-0 f_size_18 l_height30 f_p f_400"></h6>
                                </blockquote>
                                -->

                                <div class="post_share" style="margin-top: 50px;">
                                    <div class="post-nam"> Share: </div>
                                    <div class="flex">
                                        <a href="#"><i class="ti-facebook"></i>Facebook</a>
                                        <a href="#"><i class="ti-twitter"></i>Twitter</a>

                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="blog_post">
                            <div class="widget_title">
                                <h3 class="f_p f_size_20 t_color3">Related Post</h3>
                                <div class="border_bottom"></div>
                            </div>
                            <div class="row">
                            {% for post in related_posts.related.all %}
                                <div class="col-lg-8 col-sm-12">
                                    <div class="blog_post_item">
                                        <div class="blog_img">
                                            <img src="{{ post.get_feature_image_url }}" alt="">
                                        </div>
                                        <div class="blog_content">
                                            <div class="entry_post_info">
                                                <a href="{% url 'blogs:blog_post' post.slug %}">{{ post.created_at|date:"D d M Y" }}</a>
                                            </div>
                                            <a href="{% url 'blogs:blog_post' post.slug %}">
                                                <h5 class="f_p f_size_16 f_500 t_color">{{ post.title }}</h5>
                                            </a>
                                            <p class="f_400 mb-0">{{ post.content|safe|truncatewords:10 }}</p>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        {% if post.post_comment_post_set.all.count > 0 %}
                        <div class="widget_title mt_100">
                            <h3 class="f_p f_size_20 t_color3">Comments</h3>
                            <div class="border_bottom"></div>
                        </div>
                        {% for comment in post.post_comment_post_set.all %}
                         {% if comment.is_approved %}
                        <ul class="comment-box list-unstyled mb-0" id="{{comment.id}}">
                            <li class="post_comment">
                                <div class="media post_author mt_60">
                                    <div class="media-left">
                                        <img class="rounded-circle"
                                         src="https://secure.gravatar.com/avatar/8cdd21051a8dd11a0e3dc8300f36d31d?s=64&amp;d=mm&amp;r=g"
                                         srcset="https://secure.gravatar.com/avatar/8cdd21051a8dd11a0e3dc8300f36d31d?s=128&amp;d=mm&amp;r=g 2x"
                                         alt="">
                                       <!-- <a href="#" class="replay"><i class="ti-share"></i></a> -->
                                    </div>
                                    <div class="media-body">
                                        <h5 class="f_p t_color3 f_size_18 f_500">{{ comment.name }}</h5>
                                        <h6 class="f_p f_size_15 f_400 mb_20">{{ comment.created_at|time:"H:i" }}</h6>
                                        <p>{{ comment.comment }}</p>
                                    </div>
                                </div>

                            </li>
                        </ul>
                        {% endif %}
                         {% endfor %}
                        {% else %}
                                <div class="widget_title mt_100">
                            <h3 class="f_p f_size_20 t_color3">No Comment</h3>
                            <div class="border_bottom"></div>
                        </div>
                        {% endif %}
                                     {% if request.session.comment == '1' %}
                                        <div class="col-md-6 col-md-offset-5">
                                        <div class="alert alert-success alert-dismissible" role="alert">
                                            <button style="background-color: #fff; color: #000; padding:0" type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <b style="color: green;"><strong>Thanks,</strong> your comment is received and will be reviewed shortly!</b>
                                        </div>
                                    </div>
                                    {% endif %}


                        <div class="widget_title mt_100">
                            <h3 class="f_p f_size_20 t_color3">Leave a Comment</h3>
                            <div class="border_bottom"></div>
                        </div>
                        <form class="get_quote_form row" action="{% url 'blogs:post_comment' %}" method="post">{% csrf_token %}
                        <input type="hidden" value="{{post.id}}" name="post">
                            <div class="col-md-12 form-group">
                                <textarea class="form-control message" name="comment"  placeholder="Comment"></textarea>
                            </div>
                            <div class="col-md-6 form-group">
                                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                            </div>
                            <div class="col-md-6 form-group">
                                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                            </div>
                            <div class="col-md-12 form-group">
                                <input type="text" class="form-control" id="website" name="website" placeholder="Website (optional)">
                            </div>
                            <div class="col-md-12"><button class="btn btn_three btn_hover f_size_15 f_500" type="submit">Post Comment</button></div>
                        </form>
                    </div>


                </div>
            </div>
        </section>


{% include 'footer.html' %}
{% endblock %}