blogs/urls.py
from django.urls import path
from django.conf.urls import url

from blogs import views

app_name = 'blogs'
urlpatterns = [
    path('', views.blog_page, name="blog_page"),
    path('<year>/<month>', views.blog_by_year_month_page, name="blog_by_year_month_page"),
    path('post-comment/', views.post_comment_view, name='post_comment'),
    path('unset/', views.unset, name="unset"),
    path('<slug:slug>/', views.blog_post, name="blog_post"),
    path('category/<int:id>/', views.blog_category, name="blog_category"),
]

faqs/urls.py
from django.urls import path

from faqs import views

app_name = 'faqs'
urlpatterns = [
    path('', views.faq, name="faq"),
    path('new/', views.faq_new, name="faq_new"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from eshop import views, urls
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_page, name="index_page"),
    path('integrations', views.integrations, name="integrations_page"),
    path('case-studies', views.case_studies, name="case_studies_page"),
    path('partners', views.partners, name="partners_page"),
    path('privacy', views.privacy, name="privacy_page"),
    path('service', views.service, name="service_page"),
    path('terms', views.terms, name="terms_page"),
    path('integrations/<accounting>', views.integrations_acounting, name="integrations_acounting_page"),
    path('apps/<app>', views.product_details, name="product_details_page"),
    path('landing', include("eshop.urls")),
    path('faq/', include('faqs.urls'), name="faq_home"),
    path('blog/', include('blogs.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base-blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset='UTF-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>

    <link rel='stylesheet' href="{% static 'css-themeblog/dashicons.min.css' %}" type='text/css' />
    <link rel='stylesheet' href="{% static 'css-themeblog/theme-my-login.css' %}" type='text/css' />
    <link rel='stylesheet' href="{% static 'css-themeblog/all.min.css' %}" type='text/css'  />
    <link rel='stylesheet' href="{% static 'css-themeblog/v4-shims.min.css' %}" type='text/css' />
    <link rel='stylesheet' href="{% static 'css-themeblog/style.css' %}" type='text/css' />
    <link rel='stylesheet' href="{% static 'css-themeblog/jquery.accordion.css' %}" type='text/css' />
    <link rel='stylesheet' href="{% static 'css-themeblog/clients-bar.css' %}" type='text/css' />
    <link rel='stylesheet' href="{% static 'css-themeblog/font-awesome.min.css' %}" type='text/css' />
    <link rel='stylesheet' href="{% static 'css-themeblog/public.css' %}"
        type='text/css' />
    <link rel='stylesheet' href="{% static 'css-themeblog/woo-multi-currency.min.css' %}"
        type='text/css' />
    <link rel='stylesheet' href="{% static 'css-themeblog/flags-64.min.css' %}" type='text/css'  />
    <link rel='stylesheet' href="{% static 'css-themeblog/bootstrap.min.css' %}" type='text/css'  />
<!--    <link rel='stylesheet' id='hestia-font-sizes-css' href="{% static 'css-thameblog/font-sizes.min.css' %}" type='text/css'-->
<!--         />-->
    <link rel='stylesheet' href="{% static 'css-themeblog/font-awesome.min.css' %}" type='text/css' />
    <link rel='stylesheet' id='hestia_style-css' href="{% static 'css-themeblog/style.min.css' %}" type='text/css'  />
    <link href="https://fonts.googleapis.com/css?family=Dosis:500,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400,400i,600,700" rel="stylesheet">

<style id='hestia_style-inline-css' type='text/css'>
        .navbar:not(.navbar-transparent) li:not(.btn):hover>a,
        .navbar li.on-section:not(.btn)>a,
        .navbar.full-screen-menuF.navbar-transparent li:not(.btn):hover>a,
        .navbar.full-screen-menu .navbar-toggle:hover,
        .navbar:not(.navbar-transparent) .nav-cart:hover,
        .navbar:not(.navbar-transparent) .hestia-toggle-search:hover {
            color: #e82566
        }

        .header-filter-gradient {
            background: linear-gradient(45deg, rgba(168, 29, 132, 1) 0%, rgb(234, 57, 111) 100%);
        }

        .has-header-gradient-color {
            color: #a81d84;
        }

        .has-header-gradient-background-color {
            background-color: #a81d84;
        }
        .navbar .navbar-nav>li>a {
            color: #e30586 !important;
            text-transform: none;
            font-size: 18px;
        }
    </style>

    <style type="text/css">
        /* Add your CSS code here.

        For example:
        .example {
            color: red;
        }

        For brushing up on your CSS knowledge, check out http://www.w3schools.com/css/css_syntax.asp

        End of comment */

        .toggle-switch {
            background: #ccc;
            width: 80px;
            height: 30px;
            overflow: hidden;
            border-radius: 3px;
            display: inline-block;
            vertical-align: middle;
            margin: 0 10px;

            &:after {
                content: " ";
                display: block;
                width: 40px;
                height: 30px;
                background-color: #3498DB;
                border: 3px solid #fff;
                border-top: 0;
                border-bottom: 0;
                margin-left: -3px;
                transition: all 0.1s ease-in-out;
            }

            .active & {
                &:after {
                    margin-left: 40px;
                }
            }
        }

        .toggle-label {
            display: inline-block;
            line-height: 30px;
        }

        .toggle-label-off {
            color: #3498DB;
        }

        .active {

            .toggle-label-off {
                color: #000;
            }

            .toggle-label-on {
                color: #3498DB;
            }
        }
    </style>
    <!-- end Simple Custom CSS and JS -->
    <noscript>

    </noscript>
    <style type="text/css" id="custom-background-css">
        body.custom-background {
            background-color: #000000;
        }
    </style>

    <style type="text/css" id="wp-custom-css">
        .copyright.pull-right {
            display: none;
        }

        .hestia-testimonials-content {
            height: 0px;
        }


        * {
            font-family: "Dosis", sans-serif;
        }

        p {
            color: #000;
        }

        h5.description {
            color: #000;
        }

        .hestia-features .hestia-info p {
            color: #000;
        }

        .card-description {
            color: #000;
        }

        /*remove buttons*/



        ul,
        ol,
        .blog-post .section-text p,
        output {
            color: #000;
            font-size: 19px !important;
        }

        .subscription-next-payment.order-date span {
            display: none;
        }

        .subscription-next-payment.order-date:after {
            content: "Kommande betalning"
        }
        .navbar-fixed-top .navbar-nav > li > a.discover-btn:hover {
    border: 1px solid #e30586;
    color: #fff !important;
    background: #3dd6eb;
}
.navbar-fixed-top .navbar-nav > li > a.discover-btn {
    color: #e30586 !important;
    background: transparent;
    border: 1px solid #e30586;
    border-radius: 8px 8px;
    padding: 12px 18px !important;
    margin-left: 10px;
    margin-right: 15px;
    font-family: "Dosis", sans-serif;
}
.footer {
    position: relative;
    overflow: hidden;
    display: block;
    margin-top: 30px;
    padding: 60px 0 55px 0;
    background-color: #14030d;
}
#newsletter-form #email_newsletter {
    width: 100%;
    max-width: 280px;
    height: 65px;
    padding: 0 20px;
    border: 2px solid #fff;
    background-color: transparent;
    -moz-border-radius: 5px 5px 5px 5px;
    -webkit-border-radius: 5px 5px 5px 5px;
    border-radius: 5px 5px 5px 5px;
    color: #fff;
    font-size: 16px;
    margin: 0;
}
.footer p {
    color: #fff;
}
.footer-heading {
    margin-bottom: 15px;
    font-weight: 600px;
    color: #fff;
}
.footer-text a {
    text-decoration: none !important;
}
.footer p a {
    font-size: 16px;
    color: #fff;
    text-decoration: underline;
}
element.style {
    background-color: #02a4b8;
    color: #000;
    margin-top: 6px;
    height: 40px;
    padding: 0 5px 5px 5px;
}
.btn-blue:hover {
    box-shadow: 0px 4px 10px 0 rgba(0, 0, 0, 0.5);
    color: #fff !important;
    background: #3dd6eb;
}
*, ::after, ::before {
    box-sizing: border-box;
}
.btn:not(:disabled):not(.disabled) {
    cursor: pointer;
}
.btn-blue {
    font-family: "Dosis", sans-serif;
    font-size: 18px;
    line-height: 22px;
    font-weight: 600;
    color: #fff;
    background-color: #02a4b8;
    box-shadow: 0px 8px 40px 0 rgba(0, 0, 0, 0.37);
    text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.25);
    letter-spacing: 1px;
    border-radius: 5px 5px;
    margin: 10px 10px 0 10px 0;
    padding: 20px 30px;
    display: inline-block;
    transition: all 0.4s ease-in-out;
    -webkit-transition: all 0.4s ease-in-out;
}
.btn {
    display: inline-block;
    font-weight: 400;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    border: 1px solid transparent;
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    border-radius: .25rem;
    transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
h1,
        h2,
        h3,
        h4,
        h5,
        h6,
        .hestia-title,
        .hestia-title.title-in-content,
        p.meta-in-content,
        .info-title,
        .card-title,
        .page-header.header-small .hestia-title,
        .page-header.header-small .title,
        .widget h5,
        .hestia-title,
        .title,
        .footer-brand,
        .footer-big h4,
        .footer-big h5,
        .media .media-heading,
        .carousel h1.hestia-title,
        .carousel h2.title,
        .carousel span.sub-title,
        .woocommerce.single-product h1.product_title,
        .woocommerce section.related.products h2,
        .hestia-about h1,
        .hestia-about h2,
        .hestia-about h3,
        .hestia-about h4,
        .hestia-about h5 {
            font-family: Arial, Helvetica, sans-serif;
        }
        .btn.btn-primary,
        .btn.btn-primary:link,
        .btn.btn-primary:hover,
        .btn.btn-primary:focus,
        .btn.btn-primary:active,
        .btn.btn-primary.active,
        .btn.btn-primary.active:focus,
        .btn.btn-primary.active:hover,
        .btn.btn-primary:active:hover,
        .btn.btn-primary:active:focus,
        .btn.btn-primary:active:hover,
        .label.label-primary,
        .hestia-work .portfolio-item:nth-child(6n+1) .label,
        .nav-cart .nav-cart-content .widget .buttons .button,
        .has-accent-background-color {
            background-color: #E82566;
        }
        .hestia-top-bar .widget .label-floating input[type=search]:-webkit-autofill {
            -webkit-box-shadow: inset 0 0 0px 9999px #363537
        }
        .hestia-top-bar,
        .hestia-top-bar .widget .label-floating input[type=search],
        .hestia-top-bar .widget.widget_search form.form-group:before,
        .hestia-top-bar .widget.widget_product_search form.form-group:before,
        .hestia-top-bar .widget.widget_shopping_cart:before {
            color: #FFFFFF
        }
        .hestia-top-bar .widget .label-floating input[type=search] {
            -webkit-text-fill-color: #FFFFFF !important
        }
    </style>
<link rel="icon" href="{% static 'image-theme/favicon.png'%}">

</head>


<body>

    {% block content %}
    {% endblock %}


<script type='text/javascript' src="{% static 'js-themeblog/jquery.js' %}">
    </script>
        <script type='text/javascript' src="{% static 'js-themeblog/bootstrap.min.js' %}">
    </script>
    <script type='text/javascript'
        src="{% static 'js-themeblog/jquery-migrate.min.js' %}"></script>
    <script type='text/javascript'>
        /* <![CDATA[ */
    var ctPublic = {"_ajax_nonce":"abba51a0bc","_ajax_url":"https:\/\/automatiseramera.se\/wp-admin\/admin-ajax.php"};
    /* ]]> */
    </script>
    <script type='text/javascript'
        src="{% static 'js-themeblog/apbct-public.js' %}">
    </script>
    <script type='text/javascript'>
        /* <![CDATA[ */
    var ctNocache = {"ajaxurl":"https:\/\/automatiseramera.se\/wp-admin\/admin-ajax.php","info_flag":"","set_cookies_flag":"","blog_home":"https:\/\/automatiseramera.se\/"};
    /* ]]> */
    </script>
<!--    <script type='text/javascript'-->
<!--        src="{% static 'js-themeblog/cleantalk_nocache.js' %}">-->
<!--    </script>-->
    <script type='text/javascript'>
        /* <![CDATA[ */
    var pf = {"spam":{"label":"I'm human!","value":"f1857ef4cf"}};
    /* ]]> */
    </script>
    <script type='text/javascript'
        src=" {% static 'js-themeblog/custom-spam.js' %}"></script>
    <script type='text/javascript'
        src=" {% static 'js-themeblog/jquery.accordion.js' %}"></script>
    <script type='text/javascript'
        src="{% static 'js-themeblog/woo-multi-currency.min.js' %}">
    </script>



    <!-- start Simple Custom CSS and JS -->


    <script type="text/javascript">
        var weekday = null;
    var stripe_user_id = null;
    var stripe_access_token = null;

    jQuery(document).ready(function() {
        jQuery(".dropdown-menu li a").click(function() {
            weekday = jQuery(this).text(); ///User selected value...****
            console.log(weekday);
            jQuery(this).addClass('active');
            jQuery(this).parents('.btn-group').find('.dropdown-toggle').html(weekday + ' <span class="caret"></span>');
        });
    });




    </script>
    <!-- end Simple Custom CSS and JS -->
    <!-- start Simple Custom CSS and JS -->
    <script type="text/javascript">
        jQuery(document).ready(function(){
        jQuery("input[name='is_vat_registered']").on('change', check_is_vat_registered);

        function check_is_vat_registered() {
            var is_vat_reg = jQuery("input[name='is_vat_registered']").is(':checked');
            if(is_vat_reg){
                jQuery('div#is_vat_registered').slideDown();
            } else {
                jQuery('div#is_vat_registered').slideUp();
            }
        }
    });
    </script>
    <script>
        jQuery(document).ready(function(){
            jQuery('.close').on('click', close_button_clicked);
            function close_button_clicked() {
                jQuery.ajax({
                url: "{% url 'blogs:unset' %}",
                type: "GET",
                success: function(data) {
                    if(data['success'] == true) {
                        return;
                    }
                    else {
                        alert("There is an error in posting comment");
                    }
                },
                error: function() {
                    alert("There is an error");
                }
                });
             }
    });
    </script>
</body>

templates/base-faqnew.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FAQ</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css-theme/all.min.css'%}">
    <link rel="stylesheet" href="{% static 'css-themefaq/faq-style.css' %}">
    <link rel="shortcut icon" href="{% static 'image-theme/favicon.png'%}">
    <link href="https://fonts.googleapis.com/css?family=Dosis:500,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400,400i,600,700" rel="stylesheet">
</head>
<body>

{% block content %}
{% endblock %}
<script>
    	$('.side-link').on('click', function(event) {
    		var target = $(this.getAttribute('href'));
		    if( target.length ) {
		        event.preventDefault();
		        $('html, body').stop().animate({
		            scrollTop: target.offset().top
		        }, 1000);
		    }
		});

		$(window).scroll(function() {
		    var windscroll = $(window).scrollTop();
		    if (windscroll >= 100) {
		        $('.faq-container').each(function(i) {
		            if ($(this).position().top <= windscroll - 20) {
		                $('.side-nav ul li.is_active').removeClass('is_active color-orange');
		                $('.side-nav ul li').eq(i).addClass('is_active color-orange');
		            }
		        });

		    } else {

		        $('.side-nav ul li.is_active').removeClass('is_active color-orange');
		        $('.side-nav ul li:first').addClass('is_active color-orange');
		    }

		}).scroll();
    </script>
<script>
    	$(document).ready(function(){
		    //Check to see if the window is top if not then display button
		    $(window).scroll(function(){
		        if ($(this).scrollTop() > 100) {
		            $('.scrollToTop').fadeIn();
		        } else {
		            $('.scrollToTop').fadeOut();
		        }
		    });

		    //Click event to scroll to top
		    $('.scrollToTop').click(function(){
		        $('html, body').animate({scrollTop : 0},800);
		        return false;
		    });

            if($(window).width() > 767)
            {
                var totalHeight = $('.main-content').height();
                $(window).scroll(function() {
                    var scroll = $(window).scrollTop();
                    if (scroll >= totalHeight - 200) {
                        $('.desktop-size').addClass('after-style');
                        $('.desktop-size').removeClass('before-style');
                    }
                    else {
                        $('.desktop-size').removeClass('after-style');
                        $('.desktop-size').addClass('before-style');
                    }
                });
            }
            else{
                $('.mobilesScrollToTop').click(function(){
                    $('html, body').animate({scrollTop : 0},800);
                    return false;
                });
            }
		});
    </script>
</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
 
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="">
    <meta http-equiv="refresh" name="description" id="appmetadescription" content="{{appDescription.description}}">

    <title>Connectivo - Bridging platforms made easy. </title>

    <!-- Loading Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Loading Template CSS -->
    <link href="{% static 'css-theme/style.css' %}" rel="stylesheet">
    <link href="{% static 'css-theme/animate.css'%}" rel="stylesheet">
    <link href="{% static 'css-theme/style-magnific-popup.css'%}" rel="stylesheet">

    <!-- Awsome Fonts -->
    <link rel="stylesheet" href="{% static 'css/all.min.css'%}">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Dosis:500,600" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400,400i,600,700" rel="stylesheet">

    <!-- Font Favicon -->
    <link rel="shortcut icon" href="{% static 'image-theme/favicon.png'%}">


</head>

<body>

    <!--begin header -->
    <header class="header">

        <!--begin navbar-fixed-top -->
        <nav class="navbar navbar-default navbar-fixed-top">

            <!--begin container -->
            <div class="container">

                <!--begin navbar -->
                <nav class="navbar navbar-expand-lg">

                    <!--begin logo -->
                    <a class="navbar-brand" href="">
                        <img src="{% static 'image-theme/logo.png'%}" style="width: 140px;">
                    </a>
                    <!--end logo -->

                    <!--begin navbar-toggler -->
                    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
                        data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
                    </button>
                    <!--end navbar-toggler -->

                    <!--begin navbar-collapse -->
                    <div class="navbar-collapse collapse" id="navbarCollapse" style="">

                        <!--begin navbar-nav -->
                        <ul class="navbar-nav ml-auto">

                            <li><a href="{% url 'index_page' %}">Hem</a></li>

                            <li><a href="#about">Om oss</a></li>

                            <li><a href="{% url 'integrations_page' %}">Integrationer</a></li>

                            <li><a href="{% url 'faqs:faq' %}">FAQ</a></li>

                            <li><a href="{% url 'blogs:blog_page' %}">Blogg</a></li>

                            <li><a href="#contact">Kontakt</a></li>

                            <li class="discover-link"><a href="https://integration.automatiseramera.se" class="external discover-btn">Kundportal</a>
                            </li>

                        </ul>
                        <!--end navbar-nav -->

                    </div>
                    <!--end navbar-collapse -->

                </nav>
                <!--end navbar -->

            </div>
            <!--end container -->

        </nav>
        <!--end navbar-fixed-top -->

    </header>
    <!--end header -->

<!--begin showcase section-->
    <section class="section-white" id="showcase">

        <!--begin container-->
        <div class="container-fluid">

            <!--begin row-->
            <div class="row">

                <!--begin col md 12-->
                <div class="col-md-12 text-center">

    
          
          {% block content %}
          {% endblock %}
  

</div>
                <!--end col md 12-->

            </div>
            <!--end row -->

        </div>
        <!--end container -->

    </section>

    <!-- Load JS here for greater good =============================-->
    <script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/jquery.scrollTo-min.js'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.nav.js'%}"></script>
    <script src="{% static 'js/wow.js'%}"></script>
    <script src="{% static 'js/plugins.js'%}"></script>
    <script src="{% static 'js/custom.js'%}"></script>
    <script>
    $(document).ready(function(){
        // Add minus icon for collapse element which is open by default
        $(".collapse.show").each(function(){
        	$(this).prev(".card-header").find(".fa").addClass("fa-minus").removeClass("fa-plus");
        });

        // Toggle plus minus icon on show hide of collapse element
        $(".collapse").on('show.bs.collapse', function(){
        	$(this).prev(".card-header").find(".fa").removeClass("fa-plus").addClass("fa-minus");
        }).on('hide.bs.collapse', function(){
        	$(this).prev(".card-header").find(".fa").removeClass("fa-minus").addClass("fa-plus");
        });
    });
</script>
</body>
{% include 'footer.html' %}
</html>

templates/blog-header.html
{% load static %}
    <header class="header">

        <!--begin navbar-fixed-top -->
        <nav class="navbar navbar-default navbar-fixed-top">

            <!--begin container -->
            <div class="container">

                <!--begin navbar -->
                <nav class="navbar navbar-expand-lg">

                    <!--begin logo -->
                    <a class="navbar-brand" href="">
                        <img src="{% static 'image-theme/logo.png'%}" style="width: 140px;">
                    </a>
                    <!--end logo -->

                    <!--begin navbar-toggler -->
                    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
                        data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
                    </button>
                    <!--end navbar-toggler -->

                    <!--begin navbar-collapse -->
                    <div class="navbar-collapse collapse" id="navbarCollapse">

                        <!--begin navbar-nav -->
                        <ul class="navbar-nav ml-auto">

                            <li><a href="{% url 'landing_page' %}">Hem</a></li>

                            <li><a href="#about">Om oss</a></li>

                            <li><a href="{% url 'eshop:load_page' %}">Integrationer</a></li>

                            <li><a href="{% url 'faqs:faq' %}">FAQ</a></li>

                            <li><a href="{% url 'blogs:blog_page' %}">Blogg</a></li>

                            <li><a href="#contact">Kontakt</a></li>

                            <li class="discover-link"><a href="https://integration.automatiseramera.se" class="external discover-btn">Kundportal</a>
                            </li>

                        </ul>
                        <!--end navbar-nav -->

                    </div>
                    <!--end navbar-collapse -->

                </nav>
                <!--end navbar -->

            </div>
            <!--end container -->

        </nav>
        <!--end navbar-fixed-top -->

    </header>

templates/header.html
{% load static %}
    <!--begin header -->
   <header class="header_area">
            <nav class="navbar navbar-expand-lg menu_seven">
                <div class="container">
                    <a class="navbar-brand sticky_logo" href="/"><img src="{% static 'asset/img/home/logo.png' %} " srcset="{% static 'asset/img/home/logo.png' %}" alt="logo"><img src="{% static 'asset/img/home/logo2.png' %} " srcset="{% static 'asset/img/home/logo2.png' %} " alt=""></a>
                    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="menu_toggle">
                            <span class="hamburger">
                                <span></span>
                                <span></span>
                                <span></span>
                            </span>
                            <span class="hamburger-cross">
                                <span></span>
                                <span></span>
                            </span>
                        </span>
                    </button>


                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav menu pl_120 mr-auto ml-auto">
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'index_page' %}" >
                                    Hem
                                </a>
                             
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link " href="{% url 'integrations_page' %}">
                                    Integrationer
                                </a>
                              
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link " href="{% url 'faqs:faq' %}" >
                                    FAQ
                                </a>
                               
                            </li>
                            <li class="nav-item dropdown submenu">
                                <a class="nav-link dropdown-toggle" href="{% url 'case_studies_page' %}">
                                    Kundcases
                                </a>
                            </li>
                            <li class="nav-item dropdown submenu">
                                <a class="nav-link dropdown-toggle" href="{% url 'blogs:blog_page' %}">
                                    Blogg
                                </a>
                            </li> 
                            <li class="nav-item dropdown submenu mega_menu">
                                <a class="nav-link dropdown-toggle" href="#contact" >
                                    Kontat
                                </a>
                               
                            </li>
                             <li class="nav-item search"><a class="nav-link search-btn" href="javascript:void(0);"><i class="ti-search"></i></a></li>
                        </ul>
                        <a class="btn_get btn_hover btn_get_radious Cus_seven" href="https://integration.automatiseramera.se">Kundportal</a>
                        
                    </div>
                      
                </div>
            </nav>
        </header>
    <!--end header -->